name: Build docker image

on: 
  push: 
    branches:
      - develop   

jobs:
   build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Login to docker 
        run: echo ${{secrets.DOCKER_PASSWORD}} | 
             docker login -u $
             {{secrets.DOCKER_USERNAME}}
             --password-stdin 
        
      - name: Build docker image
        run: docker build -t smitalipatekar/test-image . 

      - name: Push docker image
        run: docker push smitalipatekar/test-image
