name: Build docker image

on: 
  push: 
    branches:
      - develop   

jobs:
   build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build docker image
        run: docker build -t smitalipatekar/test-image . 

      - name: Push docker image
        run: docker push smitalipatekar/test-image
